version: '3.8'
services:
  front:
    build:
      context: ./front/
      target: dev
    volumes:
      - ./front/api:/front/api
      - ./front/components:/front/components
      - ./front/contexts:/front/contexts
      - ./front/data:/front/data
      - ./front/pages:/front/pages
      - ./front/public:/front/public
      - ./front/styles:/front/styles
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - titinetwork
    restart: always

networks:
  titinetwork:
    driver: bridge
