version: '3.8'
services:
  front:
    container_name: titifront
    build:
      context: ./front/
      target: production
      # network: host
    command: npm run prod
    ports:
      - "3000:3000"
    networks:
      - titinetwork
    # network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  titinetwork:
    external: true
    name: titinetwork
