version: '3.8'
services:
  front:
    build:
      context: ./front/
      target: production
      # network: host
    command: npm run start
    ports:
      - "3000:3000"
    networks:
      titilan:
    restart: always
    depends_on:
      - back

networks:
  titilan:
    driver: bridge
