version: '3.8'
services:
  back:
    build:
      context: ./back/
      target: production
    command: pm2-runtime dist/index.js
    ports:
      - "5000:5000"
    networks:
      - dockerlan
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  front:
    build:
      context: ./front/
      target: production
    command: npm run start
    ports:
      - "3000:3000"
    networks:
      - dockerlan
    restart: always
    depends_on:
      - back

networks:
  dockerlan:
    driver: bridge
