version: '3.8'
services:
  back:
    build:
      context: ./back/
      target: dev
    volumes:
      - ./back:/src
    command: npm run start:dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    networks:
      - dockerlan
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  front:
    build:
      context: ./front/
      target: dev
    volumes:
      - ./front:/app
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - dockerlan
    restart: always
    depends_on:
      - back

networks:
  dockerlan:
    driver: bridge
