version: '3.8'
services:
  front:
    build:
      context: ./front/
      target: production
      network: host
    command: npm run start
    ports:
      - "3000:3000"
    networks:
      titilan:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  titilan:
    driver: bridge
