version: '3.8'
services:
  back:
    build:
      context: ./back/
      target: production
      # network: host
    command: pm2-runtime dist/index.js
    ports:
      - "5000:5000"
    networks:
      - dockerlan
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart: always

  front:
    build:
      context: ./front/
      target: production
      # network: host
    command: npm run start
    ports:
      - "3000:3000"
    networks:
      front_dockerlan:
        external: true
    restart: always
    depends_on:
      - back

# networks:
#   dockerlan:
#     external: true
